import json

NB_PATH = 'notebooks/JaikishanNayak_AirQualityAnalytics.ipynb'

with open(NB_PATH, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Map of cell-id -> list of exact source lines (safe, no embedded newlines in strings)
cell_fixes = {

"interp-perm-plot-code": [
    "# ── Horizontal bar chart: top 15 permutation importances ─────────────────────\n",
    "top15 = perm_importance_df.head(15).copy()[::-1]  # reverse for horizontal plot\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(10, 7))\n",
    "colors = ['#d62728' if f in POLLUTANT_FEATURES else\n",
    "          '#1f77b4' if f in TEMPORAL_FEATURES  else\n",
    "          '#2ca02c'\n",
    "          for f in top15['Feature']]\n",
    "bars = ax.barh(top15['Feature'], top15['Importance_Mean'], xerr=top15['Importance_Std'],\n",
    "               color=colors, edgecolor='white', capsize=3)\n",
    "ax.set_xlabel('Mean Permutation Importance (R2 drop when feature shuffled)')\n",
    "ax.set_title('Top 15 Feature Importances (Permutation, n=10 repeats) -- Red=pollutant | Blue=temporal | Green=city')\n",
    "ax.axvline(0, color='black', linewidth=0.8)\n",
    "from matplotlib.patches import Patch\n",
    "legend_elements = [Patch(facecolor='#d62728', label='Pollutant'),\n",
    "                   Patch(facecolor='#1f77b4', label='Temporal'),\n",
    "                   Patch(facecolor='#2ca02c', label='City')]\n",
    "ax.legend(handles=legend_elements, fontsize=9, loc='lower right')\n",
    "plt.tight_layout()\n",
    "plt.show()",
],

"interp-range-code": [
    "# ── Error by AQI range ────────────────────────────────────────────────────────\n",
    "def aqi_range_label(aqi):\n",
    "    if aqi <= 50:   return '1. Good (0-50)'\n",
    "    if aqi <= 100:  return '2. Satisfactory (51-100)'\n",
    "    if aqi <= 200:  return '3. Moderate (101-200)'\n",
    "    if aqi <= 300:  return '4. Poor (201-300)'\n",
    "    if aqi <= 400:  return '5. Very Poor (301-400)'\n",
    "    return           '6. Severe (401+)'\n",
    "\n",
    "pred_table['AQI_Range'] = pred_table['Actual_AQI'].apply(aqi_range_label)\n",
    "\n",
    "range_error = (\n",
    "    pred_table.groupby('AQI_Range')\n",
    "    .apply(lambda g: pd.Series({\n",
    "        'N':    len(g),\n",
    "        'MAE':  round(g['Abs_Error'].mean(), 2),\n",
    "        'RMSE': round(np.sqrt((g['Residual']**2).mean()), 2),\n",
    "        'Mean_Actual':    round(g['Actual_AQI'].mean(), 1),\n",
    "        'Mean_Predicted': round(g['Predicted_AQI'].mean(), 1),\n",
    "    }), include_groups=False)\n",
    "    .reset_index()\n",
    ")\n",
    "\n",
    "print('Prediction error by AQI range (post-hoc grouping -- not a predictor):')\n",
    "print(range_error.to_string(index=False))\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(11, 5))\n",
    "x     = range(len(range_error))\n",
    "width = 0.35\n",
    "bars1 = ax.bar([i - width/2 for i in x], range_error['MAE'],  width,\n",
    "               label='MAE',  color='steelblue',  edgecolor='white')\n",
    "bars2 = ax.bar([i + width/2 for i in x], range_error['RMSE'], width,\n",
    "               label='RMSE', color='darkorange', edgecolor='white')\n",
    "for bar in list(bars1) + list(bars2):\n",
    "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,\n",
    "            str(round(bar.get_height(), 0)), ha='center', va='bottom', fontsize=7.5)\n",
    "ax.set_xticks(list(x))\n",
    "ax.set_xticklabels(range_error['AQI_Range'], rotation=15, ha='right', fontsize=9)\n",
    "ax.set_ylabel('Error (AQI units)')\n",
    "ax.set_title('MAE and RMSE by Actual AQI Range (post-prediction diagnostic only)')\n",
    "ax.legend()\n",
    "plt.tight_layout()\n",
    "plt.show()",
],

"interp-city-code": [
    "# ── City-level error statistics ───────────────────────────────────────────────\n",
    "city_error = (\n",
    "    pred_table.groupby('City')\n",
    "    .apply(lambda g: pd.Series({\n",
    "        'N':              len(g),\n",
    "        'MAE':            round(g['Abs_Error'].mean(), 2),\n",
    "        'RMSE':           round(np.sqrt((g['Residual']**2).mean()), 2),\n",
    "        'Mean_Actual':    round(g['Actual_AQI'].mean(), 1),\n",
    "        'Mean_Predicted': round(g['Predicted_AQI'].mean(), 1),\n",
    "    }), include_groups=False)\n",
    "    .sort_values('MAE', ascending=False)\n",
    "    .reset_index()\n",
    ")\n",
    "\n",
    "print('City-level prediction error (sorted by MAE descending):')\n",
    "print(city_error.to_string(index=False))\n",
    "print()\n",
    "print('Note: cities with small N have less reliable error estimates.')\n",
    "\n",
    "city_plot = city_error[city_error['N'] >= 20].sort_values('MAE')\n",
    "fig, ax = plt.subplots(figsize=(10, 7))\n",
    "colors_c = ['#d62728' if v > 30 else '#ff7f0e' if v > 20 else '#2ca02c'\n",
    "            for v in city_plot['MAE']]\n",
    "bars = ax.barh(city_plot['City'], city_plot['MAE'], color=colors_c, edgecolor='white')\n",
    "for bar, (_, row) in zip(bars, city_plot.iterrows()):\n",
    "    ax.text(bar.get_width() + 0.3, bar.get_y() + bar.get_height()/2,\n",
    "            str(row['MAE']) + '  (n=' + str(int(row['N'])) + ')',\n",
    "            va='center', fontsize=8)\n",
    "ax.set_xlabel('MAE (AQI units)')\n",
    "ax.set_title('City-Level Prediction MAE (cities with N >= 20 test obs) -- Green<20 | Orange 20-30 | Red>30')\n",
    "ax.set_xlim(0, city_plot['MAE'].max() * 1.3)\n",
    "plt.tight_layout()\n",
    "plt.show()",
],

"interp-temporal-code": [
    "# ── Monthly error on test set ─────────────────────────────────────────────────\n",
    "pred_table['Month_num'] = df_test['Date'].dt.month.values\n",
    "\n",
    "month_labels_map = {12:'Dec-19', 1:'Jan-20', 2:'Feb-20', 3:'Mar-20',\n",
    "                4:'Apr-20', 5:'May-20', 6:'Jun-20', 7:'Jul-20'}\n",
    "\n",
    "temporal_error = (\n",
    "    pred_table.groupby('Month_num')\n",
    "    .apply(lambda g: pd.Series({\n",
    "        'Month':  month_labels_map.get(g['Month_num'].iloc[0], str(g['Month_num'].iloc[0])),\n",
    "        'N':      len(g),\n",
    "        'MAE':    round(g['Abs_Error'].mean(), 2),\n",
    "        'RMSE':   round(np.sqrt((g['Residual']**2).mean()), 2),\n",
    "        'Mean_Actual': round(g['Actual_AQI'].mean(), 1),\n",
    "    }), include_groups=False)\n",
    "    .reset_index()\n",
    "    .sort_values('Month_num')\n",
    ")\n",
    "\n",
    "print('Monthly error on test set:')\n",
    "print(temporal_error[['Month','N','MAE','RMSE','Mean_Actual']].to_string(index=False))\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(10, 4))\n",
    "ax.plot(temporal_error['Month'], temporal_error['MAE'],  marker='o', label='MAE',\n",
    "        color='steelblue', linewidth=2, markersize=7)\n",
    "ax.plot(temporal_error['Month'], temporal_error['RMSE'], marker='s', label='RMSE',\n",
    "        color='darkorange', linewidth=2, markersize=7)\n",
    "for _, row in temporal_error.iterrows():\n",
    "    ax.annotate(str(row['MAE']), (row['Month'], row['MAE']),\n",
    "                textcoords='offset points', xytext=(0, 6), ha='center', fontsize=7.5, color='steelblue')\n",
    "ax.set_xlabel('Month (test set: Dec 2019 to Jul 2020)')\n",
    "ax.set_ylabel('Error (AQI units)')\n",
    "ax.set_title('Monthly MAE and RMSE on Test Set (Jul-20 has only 24 obs)')\n",
    "ax.legend()\n",
    "plt.tight_layout()\n",
    "plt.show()",
],
}

fixed = 0
for cell in nb['cells']:
    cid = cell.get('id', '')
    if cid in cell_fixes:
        cell['source'] = cell_fixes[cid]
        print('Fixed:', cid)
        fixed += 1

with open(NB_PATH, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print(f'Fixed {fixed} cells. Saved.')
